#!/bin/bash
#for linux only
kill $(cat bot.pid)
cd ~/cloud-bot
git update-index --skip-worktree users.txt
git update-index --skip-worktree output.log
git update-index --skip-worktree bot.pid
git ls-files files/ | xargs git update-index --skip-worktree
git ls-files -v | grep ^S
git pull origin main
nohup python3 bot.py > output.log 2>&1 & echo $! > bot.pid
